// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDRpOGf2nHu5mdnM8qNVh_rdp2Zux9CCA',
    appId: '1:600182812832:web:ae426267687abe560f19c5',
    messagingSenderId: '600182812832',
    projectId: 'chatapp-405b5',
    authDomain: 'chatapp-405b5.firebaseapp.com',
    storageBucket: 'chatapp-405b5.appspot.com',
    measurementId: 'G-EP7L59X6R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQQOV6gqFAjny9_-C7BIH8rBbM17TSwM',
    appId: '1:600182812832:android:ec0d3f9b581e1ea30f19c5',
    messagingSenderId: '600182812832',
    projectId: 'chatapp-405b5',
    storageBucket: 'chatapp-405b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvo4locwYBi9EuuKA6PPRahWTjrc-ngDo',
    appId: '1:600182812832:ios:3dd7d07fd403b2870f19c5',
    messagingSenderId: '600182812832',
    projectId: 'chatapp-405b5',
    storageBucket: 'chatapp-405b5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvo4locwYBi9EuuKA6PPRahWTjrc-ngDo',
    appId: '1:600182812832:ios:3dd7d07fd403b2870f19c5',
    messagingSenderId: '600182812832',
    projectId: 'chatapp-405b5',
    storageBucket: 'chatapp-405b5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDRpOGf2nHu5mdnM8qNVh_rdp2Zux9CCA',
    appId: '1:600182812832:web:06a91067c542ccc80f19c5',
    messagingSenderId: '600182812832',
    projectId: 'chatapp-405b5',
    authDomain: 'chatapp-405b5.firebaseapp.com',
    storageBucket: 'chatapp-405b5.appspot.com',
    measurementId: 'G-5L43ZWX33J',
  );
}
